var tipuesearch = {"pages": [{'title': 'About', 'text': '我的倉儲 \n \n', 'tags': '', 'url': 'About.html'}, {'title': '每周進度', 'text': '', 'tags': '', 'url': '每周進度.html'}, {'title': 'W1', 'text': '', 'tags': '', 'url': 'W1.html'}, {'title': 'SolidWorks', 'text': '我的分工 \n 22~32 \n 零件下載 \n \n \n \n \n \n \n \n \n \n ---------------------------------------------------------------------------------------------------------------- \n', 'tags': '', 'url': 'SolidWorks.html'}, {'title': 'Onshape', 'text': '我的分工 \n 3-6~3-10 \xa0,\xa0 3-11~3-15  ,\xa0 4-1~4-3 \n \n \n \n \n \n --------------------------------------------------------------------------------------------------------------- \n', 'tags': '', 'url': 'Onshape.html'}, {'title': '零件體積', 'text': '\n', 'tags': '', 'url': '零件體積.html'}, {'title': '整組進度', 'text': 'PDF_1: \n \xa0 \xa0 \xa0 \xa0\xa0 \xa0  1~10 \n \xa0 \xa0 \xa0 \xa0 \xa0\xa0 11~21 \n \xa0 \xa0 \xa0 \xa0 \xa0  22~32 \n \xa0 \xa0 \xa0 \xa0 \xa0  43~50 \n PDF_2: \n \xa0 \xa0 \xa0 \xa0 \xa0  1-1~3-5 \n \xa0 \xa0 \xa0 \xa0 \xa0  3-6~3-14 \n \xa0 \xa0 \xa0 \xa0 \xa0  3-17~22 \n \xa0 \xa0 \xa0 \xa0 \xa0  4-1~4-3 \n', 'tags': '', 'url': '整組進度.html'}, {'title': 'W2', 'text': '', 'tags': '', 'url': 'W2.html'}, {'title': 'nxopen_getting_started_v12.pdf', 'text': 'nxopen_getting_started_v12.pdf \n', 'tags': '', 'url': 'nxopen_getting_started_v12.pdf.html'}, {'title': 'W3', 'text': '分組結果: \n 分組倉儲: \xa0 https://github.com/40823246/cad2020bg4 分組網站: \xa0 http://40823246.github.io/cad2020bg4 \n Repository: \xa0 40823207 \xa0 | Site: \xa0 40823207 Repository: \xa0 40823208 \xa0 | Site: \xa0 40823208 Repository: \xa0 40823216 \xa0 | Site: \xa0 40823216 Repository: \xa0 40823218 \xa0 | Site: \xa0 40823218 Repository: \xa0 40823220 \xa0 | Site: \xa0 40823220 Repository: \xa0 40823224 \xa0 | Site: \xa0 40823224 Repository: \xa0 40823228 \xa0 | Site: \xa0 40823228 Repository: \xa0 40823238 \xa0 | Site: \xa0 40823238 Repository: \xa0 40823244 \xa0 | Site: \xa0 40823244 Repository: \xa0 40823246 \xa0 | Site: \xa0 40823246 \xa0 (組長) \n', 'tags': '', 'url': 'W3.html'}, {'title': 'w4', 'text': 'pdf1_29 \n \n', 'tags': '', 'url': 'w4.html'}, {'title': 'w7', 'text': '', 'tags': '', 'url': 'w7.html'}, {'title': '試用ANSI C', 'text': '阻尼=1 \n \n file \n', 'tags': '', 'url': '試用ANSI C.html'}, {'title': 'w8', 'text': 'NX API 試用 \n 1.把路徑改成自想要的路徑 \n 111.py \n # nx_open_part.py\n# 導入 NXOpen\nimport NXOpen\nimport NXOpen.UF\nimport NXOpen.Gateway\n   \ndef main():\n    # 取得目前開啟的工作階段\n    theSession = NXOpen.Session.GetSession()\n    theUfSession = NXOpen.UF.UFSession.GetUFSession()\n      \n    # 建立 ListingWindow\n    listWin= theSession.ListingWindow\n    # 開啟零件檔案\n    basePart1 = theSession.Parts.OpenBaseDisplay("y:/tmp/block.prt")\n    workPart = theSession.Parts.Work\n    unit1 = workPart.UnitCollection.FindObject("MilliMeter")\n    # height\n    p7 = workPart.Expressions.FindObject("p7")\n    # width\n    p8 = workPart.Expressions.FindObject("p8")\n    # length\n    p9 = workPart.Expressions.FindObject("p9")\n    workPart.Expressions.EditWithUnits(p7, unit1, "30")\n    workPart.Expressions.EditWithUnits(p8, unit1, "60")\n    workPart.Expressions.EditWithUnits(p9, unit1, "90")\n    theSession.UpdateManager.DoUpdate(0)\n    #saveStatus1 = workPart.SaveAs("y:/tmp/block_new.prt")\n    #saveStatus1.Dispose()\n    # initialize list to hold bodies\n    theBodyTags = []\n   \n    for x in workPart.Bodies:\n        if x.IsSolidBody:\n            theBodyTags.append(x.Tag)\n      \n    # 準備輸出 ASCII 格式 STL 零件檔案\n    sTLCreator1 = theSession.DexManager.CreateStlCreator()\n    sTLCreator1.AutoNormalGen = True\n    sTLCreator1.ChordalTol = 0.08\n    sTLCreator1.AdjacencyTol = 0.08\n    sTLCreator1.OutputFile = "y:\\\\tmp\\\\block_ascii.stl"\n    # Binary STL: NXOpen.STLCreatorOutputTypeEnum.Binary\n    sTLCreator1.OutputType = NXOpen.STLCreatorOutputTypeEnum.Text\n    # 已知 body1 命名\n    body1 = workPart.Bodies.FindObject("EXTRUDE(2)")\n    added1 = sTLCreator1.ExportSelectionBlock.Add(body1)\n    nXObject1 = sTLCreator1.Commit()\n    sTLCreator1.Destroy()\n  \n    # 開啟所建立的 ListingWindow\n    listWin.Open()\n    listWin.WriteLine("number of solid bodies: " + str(len(theBodyTags)))\n   \n    (massProps, Stats) = theUfSession.Modeling.AskMassProps3d(theBodyTags, len(theBodyTags), 1, 4, .03, 1, [0.99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])\n    listWin.WriteLine("units: kg, mm")\n    listWin.WriteLine("surface area: " + str(massProps[0]))\n    listWin.WriteLine("volume: " + str(massProps[1]*1E9))\n    # 在 ListingWindow 中寫入字串\n    listWin.WriteLine("Hello, NXOpen")\n    listWin.Close()\n     \n    # 將零件檔案 fit 之後, export 出 png 檔案\n    theUI = NXOpen.UI.GetUI()\n    imageExportBuilder1 = theUI.CreateImageExportBuilder()\n \n    custombackgroundcolor1 = [None] * 3\n    custombackgroundcolor1[0] = 1.0\n    custombackgroundcolor1[1] = 1.0\n    custombackgroundcolor1[2] = 1.0\n \n    imageExportBuilder1.SetCustomBackgroundColor(custombackgroundcolor1)\n    imageExportBuilder1.FileFormat = NXOpen.Gateway.ImageExportBuilder.FileFormats.Png\n    imageExportBuilder1.FileName = "y:\\\\tmp\\\\block.png"\n \n    imageExportBuilder1.BackgroundOption = NXOpen.Gateway.ImageExportBuilder.BackgroundOptions.Original\n \n    imageExportBuilder1.EnhanceEdges = False\n    imageExportBuilder1.RegionMode = False\n    # fit view 後 commit export png\n    workPart.ModelingViews.WorkView.Fit()\n    nXObject6 = imageExportBuilder1.Commit()\n \n    imageExportBuilder1.Destroy()\n      \nif __name__ == "__main__":\n    main() \n \n 2.開啟NX隨身版，找到journal後Play程式，得到以下檔案 \n block.prt \n block_ascii.stl.txt \n \n', 'tags': '', 'url': 'w8.html'}, {'title': '筆記', 'text': '', 'tags': '', 'url': '筆記.html'}, {'title': '如何新增檔案連結', 'text': '\n 1.將檔案放入倉儲近端的downloads資料夾。 \n \n 2.到編輯網頁點edit link \n \n 3.點選檔案。 \n', 'tags': '', 'url': '如何新增檔案連結.html'}]};