<h1>About</h1>
<h4><a href="https://github.com/40823246/cad2020">我的倉儲</a></h4>
<h4></h4>
<h1>每周進度</h1>
<h2>W1</h2>
<h3>SolidWorks</h3>
<p><strong>我的分工</strong></p>
<h4><strong>22~32</strong></h4>
<p><a href="https://drive.google.com/file/d/1lzh36N4hb9T8kM3fXd6wzapzZEeanz5i/view?usp=sharing">檔案</a></p>
<p><img alt="" height="301" src="/images/22改.jpg" width="400"/></p>
<p><img alt="" height="335" src="/images/23改.jpg" width="400"/></p>
<p><img alt="" height="363" src="/images/24改.jpg" width="400"/></p>
<p><img alt="" height="378" src="/images/25改.jpg" width="400"/></p>
<p><img alt="" height="357" src="/images/28改.jpg" width="400"/></p>
<p><img alt="" height="391" src="/images/29改.jpg" width="400"/></p>
<p><img alt="" height="379" src="/images/30改.jpg" width="400"/></p>
<p><img alt="" height="382" src="/images/31改.jpg" width="400"/></p>
<p><img alt="" height="376" src="/images/32改.jpg" width="400"/></p>
<p>----------------------------------------------------------------------------------------------------------------</p>
<h3>Onshape</h3>
<p><strong>我的分工</strong></p>
<h4><strong><a href="https://cad.onshape.com/documents/5e9fd0efa83026fb32bada57/w/e9fc4e247fd8a2fdae942cda/e/a46c9307eb190dc9896ab477">3-6~3-10</a> , <a href="https://cad.onshape.com/documents/5e9fd0efa83026fb32bada57/w/e9fc4e247fd8a2fdae942cda/e/a46c9307eb190dc9896ab477">3-11~3-15</a> , <a href="https://cad.onshape.com/documents/49d5acfd1d12b0e09046c8e2/w/3b25ba61b8cee8eb29fe8efa/e/d3e1a0b28036345ab43a143d">4-1~4-3</a></strong></h4>
<p><strong><img alt="" height="246" src="/images/3-10改.jpg" width="400"/></strong></p>
<p><strong><img alt="" height="261" src="/images/3-15改.jpg" width="400"/></strong></p>
<p><strong><img alt="" height="464" src="/images/1600782955245.jpg" width="400"/></strong></p>
<p><strong><img alt="" height="411" src="/images/1600782825202.jpg" width="400"/></strong></p>
<p><strong><img alt="" height="391" src="/images/1600782740318.jpg" width="400"/></strong></p>
<p>---------------------------------------------------------------------------------------------------------------</p>
<h3>零件體積</h3>
<p><iframe height="1000" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vT8kqEWxCnP-IYOQSHiSVZDxP5PALsOsTr7R98W91FnibQDIoEeojJZmNdp7ubl-7pDP3pl2PTJvujQ/pubhtml?gid=0&amp;single=true&amp;widget=true&amp;headers=false" width="600"></iframe></p>
<h3>整組進度</h3>
<p>PDF_1:</p>
<p>           <a href="https://40823220.github.io/cad2020/content/inventor%C2%A0%20%C2%A0pdf1.html">1~10</a></p>
<p>          <a href="https://40823208.github.io/cad2020/content/%E5%80%8B%E4%BA%BA%E9%80%B2%E5%BA%A6.html">11~21</a></p>
<p>          <a href="https://40823246.github.io/cad2020/content/SolidWorks.html">22~32</a></p>
<p>          <a href="https://40823218.github.io/cad2020/content/w1%20SolidWorks%E9%9B%B6%E4%BB%B6%E7%B9%AA%E5%9C%96%E7%B7%B4%E7%BF%921(43~50).html">43~50</a></p>
<p>PDF_2:</p>
<p>          <a href="https://40823220.github.io/cad2020/content/inventor%C2%A0%20%C2%A0pdf2.html">1-1~3-5</a></p>
<p>          <a href="https://40823246.github.io/cad2020/content/Onshape.html">3-6~3-14</a></p>
<p>          <a href="https://40823208.github.io/cad2020/content/%E5%80%8B%E4%BA%BA%E9%80%B2%E5%BA%A6.html">3-17~22</a></p>
<p>          <a href="https://40823246.github.io/cad2020/content/Onshape.html">4-1~4-3</a></p>
<h2>W2</h2>
<h3>nxopen_getting_started_v12.pdf</h3>
<p><a href="http://mde.tw/cad2020/downloads/nx_python_examples.pdf">nxopen_getting_started_v12.pdf</a></p>
<h2>W3</h2>
<p>分組結果:</p>
<p>分組倉儲:<span> </span><a href="https://github.com/40823246/cad2020bg4">https://github.com/40823246/cad2020bg4</a><br/><br/>分組網站:<span> </span><a href="http://40823246.github.io/cad2020bg4">http://40823246.github.io/cad2020bg4</a></p>
<p>Repository:<span> </span><a href="https://github.com/40823207/cad2020">40823207</a><span> </span>| Site:<span> </span><a href="https://40823207.github.io/cad2020">40823207</a><br/>Repository:<span> </span><a href="https://github.com/40823208/cad2020">40823208</a><span> </span>| Site:<span> </span><a href="https://40823208.github.io/cad2020">40823208</a><br/>Repository:<span> </span><a href="https://github.com/40823216/cad2020">40823216</a><span> </span>| Site:<span> </span><a href="https://40823216.github.io/cad2020">40823216</a><br/>Repository:<span> </span><a href="https://github.com/40823218/cad2020">40823218</a><span> </span>| Site:<span> </span><a href="https://40823218.github.io/cad2020">40823218</a><br/>Repository:<span> </span><a href="https://github.com/40823220/cad2020">40823220</a><span> </span>| Site:<span> </span><a href="https://40823220.github.io/cad2020">40823220</a><br/>Repository:<span> </span><a href="https://github.com/40823224/cad2020">40823224</a><span> </span>| Site:<span> </span><a href="https://40823224.github.io/cad2020">40823224</a><br/>Repository:<span> </span><a href="https://github.com/40823228/cad2020">40823228</a><span> </span>| Site:<span> </span><a href="https://40823228.github.io/cad2020">40823228</a><br/>Repository:<span> </span><a href="https://github.com/40823238/cad2020">40823238</a><span> </span>| Site:<span> </span><a href="https://40823238.github.io/cad2020">40823238</a><br/>Repository:<span> </span><a href="https://github.com/40823244/cad2020">40823244</a><span> </span>| Site:<span> </span><a href="https://40823244.github.io/cad2020">40823244</a><br/>Repository:<span> </span><a href="https://github.com/40823246/cad2020">40823246</a><span> </span>| Site:<span> </span><a href="https://40823246.github.io/cad2020">40823246</a><span> </span>(組長)</p>
<h2>w4~w6</h2>
<p>pdf1_29</p>
<p><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen" frameborder="0" height="315" src="https://www.youtube.com/embed/fbRzil_0mfc" width="560"></iframe></p>
<h2>w7~w9</h2>
<h3>HW3</h3>
<p>1.將檔案存成ASCII STL</p>
<p>2.更改ASCII STL solid name與xml檔中的joint相對應</p>
<pre>3.調整顏色</pre>
<p><img alt="" height="325" src="/images/kr162.png" width="600"/></p>
<p></p>
<p>xml檔程式碼</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">&lt;robot_definition&gt;
&lt;robot_dk name=kmol_kr_162&gt;
&lt;axis id="Base" maxvalue="0" minvalue="0" alpha="0" a="0" theta="0" d="0"/&gt;
&lt;axis id="Joint1" limsup="185.000" liminf="-185.000" alpha="0.000" a="0.000" theta="90.000" d="640"/&gt;
&lt;axis id="Joint2" limsup="380.000" liminf="-380.000" alpha="90.000" a="-260" theta="0.000" d="0.00"/&gt;
&lt;axis id="Joint3" limsup="144.000" liminf="-100.000" alpha="0.000" a="1300.000" theta="-90.000" d="0.000"/&gt;
&lt;axis id="Joint4" limsup="350.000" liminf="-350.000" alpha="-90.000" a="-55.000" theta="0.000" d="1025.000"/&gt;
&lt;axis id="Joint5" limsup="120.000" liminf="-120.000" alpha="90.000" a="0.000" theta="0.000" d="0.000"/&gt;
&lt;axis id="Joint6" limsup="350.000" liminf="-350.000" alpha="-90.000" a="0.000" theta="180.000" d="290.000"/&gt;
&lt;/robot_dk&gt;
&lt;robot_geometry&gt;
&lt;geometry geo="kr16 - kuka kr16 assembly-1 base-2" name="Base" /&gt;
&lt;geometry geo="kr16 - kuka kr16 assembly-1 rotary head-2" name="Joint1"/&gt;
&lt;geometry geo="kr16 - kuka kr16 assembly-1 lower arm-2" name="Joint2"/&gt;
&lt;geometry geo="kr16 - kuka kr16 assembly-1 upper arm-2" name="Joint3"/&gt;
&lt;geometry geo="kr16 - kuka kr16 assembly-1 p2-2" name="Joint4"/&gt;
&lt;geometry geo="kr16 - kuka kr16 assembly-1 WRIST-2" name="Joint5"/&gt;
&lt;/robot_geometry&gt;
&lt;CAD_base x="0.000" y="0.000" z="0.000" rx="0.000" ry="0.000" rz="0.000"/&gt;
&lt;CAD_scale FACTOR="1.000000000"/&gt;
&lt;CAD_offsets cad_theta1="0.000" cad_theta2="0.000" cad_theta3="0.000" cad_theta4="0.000" cad_theta5="0.000" cad_theta6="0.000"/&gt;
&lt;Angle_Type id="1"/&gt;
&lt;/robot_definition&gt;</pre>
<p></p>
<p><a href="https://drive.google.com/file/d/19DU0PdcIAFZXHSS2Ar4XtPa4lgVYH_cQ/view?usp=sharing">檔案</a></p>
<h3>ANSI C</h3>
<p>修改啟動黨，加入tcc。</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">set path_portablegit=%Disk%:\Portablegit\bin;
set path_julia=%Disk%:\julia-1.5.2\bin;
set path_tcc=%Disk%:\tcc\;
 
path=%Disk%:;%path_python%;%path_portablegit%;%path_julia%;%path_tcc%;%path%;</pre>
<p>執行下列程式碼。</p>
<pre class="brush:html;auto-links:false;toolbar:false" contenteditable="false">/* Runge Kutta for a set of first order differential equations */
  
#include &lt;stdio.h&gt;
#include &lt;math.h&gt;
  
#define N 2 /* number of first order equations */
#define dist 0.1 /* stepsize in t*/
#define MAX 30.0 /* max for t */
  
FILE *output; /* internal filename */
FILE *output1; /* internal filename */
// 利用 pipe 呼叫 gnuplot 繪圖
FILE *pipe;
  
void runge4(double x, double y[], double step); /* Runge-Kutta function */
double f(double x, double y[], int i); /* function for derivatives */
  
void main(){
  
  double t, y[N];
  int j;
  
  output=fopen("osc.dat", "w"); /* external filename */
  output1=fopen("osc1.dat", "w"); /* external filename */
  
  y[0]=1.0; /* initial position */
  y[1]=0.0; /* initial velocity */
  
  //fprintf(output, "0\t%f\n", y[0]);
  
  for (j=1; j*dist&lt;=MAX ;j++) /* time loop */{
  
    t=j*dist;
    runge4(t, y, dist);
    fprintf(output, "%f\t%f\n", t, y[0]);
    fprintf(output1, "%f\t%f\n", t, y[1]);
  }
  
  fclose(output);
  fclose(output1);
  
  pipe = popen("gnuplot -persist","w");
  //fprintf(pipe,"set term png enhanced font \"v:/fireflysung.ttf\" 18 \n");
  fprintf(pipe,"set term png enhanced font \"y:/wqy-microhei.ttc\" 18 \n");
  //fprintf(pipe,"set yrange [68:70]\n");
  fprintf(pipe,"set output \"test.png\"\n");
  fprintf(pipe, "plot \"osc.dat\" title \"位移\" with lines, \"osc1.dat\" title \"速度\" with lines\n");
  fprintf(pipe,"quit\n");
 
  fprintf(pipe,"quit\n");
  pclose(pipe);
}
  
void runge4(double x, double y[], double step){
  
  double h=step/2.0, /* the midpoint */
  t1[N], t2[N], t3[N], /* temporary storage arrays */
  k1[N], k2[N], k3[N],k4[N]; /* for Runge-Kutta */
  int i;
  
  for (i=0;i&lt;N;i++){
  
    t1[i]=y[i]+0.5*(k1[i]=step*f(x,y,i));
  }
  
  for (i=0;i&lt;N;i++){
  
    t2[i]=y[i]+0.5*(k2[i]=step*f(x+h, t1, i));
  }
  
  for (i=0;i&lt;N;i++){
  
    t3[i]=y[i]+ (k3[i]=step*f(x+h, t2, i));
  }
  
  for (i=0;i&lt;N;i++){
  
    k4[i]= step*f(x+step, t3, i);
  }
  
  for (i=0;i&lt;N;i++){
  
    y[i]+=(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6.0;
  }
}
  
double f(double x, double y[], int i){
  
  if (i==0)
    x=y[1]; /* derivative of first equation */
  if (i==1)
    x=-y[0]-0.5*y[1];
  return x;
}</pre>
<p><br/><br/></p>
<p>阻尼=1</p>
<p><img alt="" height="480" src="/images/test.png" width="640"/></p>
<p><a href="https://drive.google.com/file/d/14zv2ZhHbZjYLV8QFJ53_gPVtcFq1epVi/view?usp=sharing">file</a></p>
<h3>NX API </h3>
<p>1.把路徑改成自想要的路徑</p>
<pre class="brush:py;auto-links:false;toolbar:false cc_cursor" contenteditable="false"># nx_open_part.py
# 導入 NXOpen
import NXOpen
import NXOpen.UF
import NXOpen.Gateway
   
def main():
    # 取得目前開啟的工作階段
    theSession = NXOpen.Session.GetSession()
    theUfSession = NXOpen.UF.UFSession.GetUFSession()
      
    # 建立 ListingWindow
    listWin= theSession.ListingWindow
    # 開啟零件檔案
    basePart1 = theSession.Parts.OpenBaseDisplay("y:/tmp/block.prt")
    workPart = theSession.Parts.Work
    unit1 = workPart.UnitCollection.FindObject("MilliMeter")
    # height
    p7 = workPart.Expressions.FindObject("p7")
    # width
    p8 = workPart.Expressions.FindObject("p8")
    # length
    p9 = workPart.Expressions.FindObject("p9")
    workPart.Expressions.EditWithUnits(p7, unit1, "30")
    workPart.Expressions.EditWithUnits(p8, unit1, "60")
    workPart.Expressions.EditWithUnits(p9, unit1, "90")
    theSession.UpdateManager.DoUpdate(0)
    #saveStatus1 = workPart.SaveAs("y:/tmp/block_new.prt")
    #saveStatus1.Dispose()
    # initialize list to hold bodies
    theBodyTags = []
   
    for x in workPart.Bodies:
        if x.IsSolidBody:
            theBodyTags.append(x.Tag)
      
    # 準備輸出 ASCII 格式 STL 零件檔案
    sTLCreator1 = theSession.DexManager.CreateStlCreator()
    sTLCreator1.AutoNormalGen = True
    sTLCreator1.ChordalTol = 0.08
    sTLCreator1.AdjacencyTol = 0.08
    sTLCreator1.OutputFile = "y:\\tmp\\block_ascii.stl"
    # Binary STL: NXOpen.STLCreatorOutputTypeEnum.Binary
    sTLCreator1.OutputType = NXOpen.STLCreatorOutputTypeEnum.Text
    # 已知 body1 命名
    body1 = workPart.Bodies.FindObject("EXTRUDE(2)")
    added1 = sTLCreator1.ExportSelectionBlock.Add(body1)
    nXObject1 = sTLCreator1.Commit()
    sTLCreator1.Destroy()
  
    # 開啟所建立的 ListingWindow
    listWin.Open()
    listWin.WriteLine("number of solid bodies: " + str(len(theBodyTags)))
   
    (massProps, Stats) = theUfSession.Modeling.AskMassProps3d(theBodyTags, len(theBodyTags), 1, 4, .03, 1, [0.99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0])
    listWin.WriteLine("units: kg, mm")
    listWin.WriteLine("surface area: " + str(massProps[0]))
    listWin.WriteLine("volume: " + str(massProps[1]*1E9))
    # 在 ListingWindow 中寫入字串
    listWin.WriteLine("Hello, NXOpen")
    listWin.Close()
     
    # 將零件檔案 fit 之後, export 出 png 檔案
    theUI = NXOpen.UI.GetUI()
    imageExportBuilder1 = theUI.CreateImageExportBuilder()
 
    custombackgroundcolor1 = [None] * 3
    custombackgroundcolor1[0] = 1.0
    custombackgroundcolor1[1] = 1.0
    custombackgroundcolor1[2] = 1.0
 
    imageExportBuilder1.SetCustomBackgroundColor(custombackgroundcolor1)
    imageExportBuilder1.FileFormat = NXOpen.Gateway.ImageExportBuilder.FileFormats.Png
    imageExportBuilder1.FileName = "y:\\tmp\\block.png"
 
    imageExportBuilder1.BackgroundOption = NXOpen.Gateway.ImageExportBuilder.BackgroundOptions.Original
 
    imageExportBuilder1.EnhanceEdges = False
    imageExportBuilder1.RegionMode = False
    # fit view 後 commit export png
    workPart.ModelingViews.WorkView.Fit()
    nXObject6 = imageExportBuilder1.Commit()
 
    imageExportBuilder1.Destroy()
      
if __name__ == "__main__":
    main()</pre>
<p></p>
<p>2.開啟NX隨身版，找到journal後Play程式，得到以下檔案</p>
<p><img alt="" height="209" src="/images/block.png" width="400"/></p>
<p><a href="https://drive.google.com/file/d/1ALYNA7lVDjsh4xiSVSESXJpIjsAt2Yq2/view?usp=sharing">檔案</a></p>
<h2>w10~14</h2>
<p><a href="https://drive.google.com/file/d/1H9WuldTJxaoj29HUVbTuXCSEaSYYnOtz/view?usp=sharing">BubbleRob tutorial.ttt</a></p>
<p><strong>小組會議</strong></p>
<p><strong>20201203</strong></p>
<p><img alt="" height="521" src="https://40823246.github.io/cad2020bg4/images/meeting1203.png" width="800"/></p>
<p><strong>20201204</strong></p>
<p><img alt="" height="239" src="https://40823246.github.io/cad2020bg4/images/meet1204.png" width="800"/></p>
<p><strong>20201211</strong></p>
<p><img alt="" height="89" src="https://40823246.github.io/cad2020bg4/images/meeting1211.png" width="800"/></p>
<p><strong>20201215</strong></p>
<p><img alt="" height="111" src="https://40823246.github.io/cad2020bg4/images/meeting1215.png" width="800"/></p>
<p><strong>20210109</strong></p>
<p><img alt="" height="395" src="https://40823246.github.io/cad2020bg4/images/meeting0109.png" width="800"/></p>
<p><strong>20210114</strong></p>
<p><img alt="" height="813" src="https://40823246.github.io/cad2020bg4/images/meeting0114.png" width="400"/></p>
<p><img alt="" height="854" src="https://40823246.github.io/cad2020bg4/images/meeting01142.png" width="400"/></p>
<p><img alt="" height="823" src="https://40823246.github.io/cad2020bg4/images/meeting01143.png" width="400"/></p>
<h1>筆記</h1>
<h2>如何新增檔案連結</h2>
<p><img alt="" height="27" src="/images/111py2.png" width="81"/></p>
<p>1.將檔案放入倉儲近端的downloads資料夾。</p>
<p><img alt="" height="235" src="/images/download.png" width="393"/></p>
<p>2.到編輯網頁點edit link</p>
<p><img alt="" height="90" src="/images/link.png" width="254"/></p>
<p>3.點選檔案。</p>
<p><img alt="" height="165" src="/images/111py.png" width="267"/><a href="/downloads/111.py"></a></p>
<h2>BubbleRob tutorial</h2>
<p><a href="https://40823246.github.io/cad2020bg4/content/BubbleRob%20tutorial.html">BubbleRob tutorial</a></p>
<h2>如何在RokiSim中更改顏色</h2>
<p>將stl檔拖入SciTE中編輯，在soild下一行加入color 0.0 0.0 0.0，</p>
<p>前面要加空格，數字的部分，分別代表藍綠紅，<span>用紅色來舉例，</span></p>
<p><span>就打color 0.0 0.0 1.0。</span></p>
<p><span>成果:</span></p>
<p><img alt="" height="445" src="/images/紅色.png" width="400"/></p>
<div id="gtx-trans" style="position: absolute; left: 15px; top: 12474.8px;">
<div class="gtx-trans-icon"></div>
</div>